### ISSUE TITLE
Handling "advanced" products and products without graphical representation 

### ISSUE THREAD

**Issue by bwilk** [cyfronet-fid/sat4envi#1020]
General characteristics:
1. More products on the "Zdjęcia satelitarne"
 
   1. 3 categories - visible, hidden and shown upon login 
2. More products searchable in the "Szukaj danych"

Functional/tech spec:
1. Frontend
   1. Use modified Sentinel search to access other types of products 
   1. Translation to polish - ("i" tooltip for the original field) #1084
   2. Product categories sorting #1083
1. Backend 
   - [x] Add an authorized_only flag to product and enforce it #1037
   - [x] Hidden products flag (download_only) - for products without graphical representation #1038
   - [x] Add an extra category in search #1040 
   - [x] Custom sorting of products and product categories #1041 (products comparable to products, categories comparable to categories)
   - [x] Search by producttype should reference product table #1039
   - [x] Correction to use metadataSchema to group products in search panel #1079
