### ISSUE TITLE
Sat4Envi Security

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#108]
## Security of GS and backend:
1.  granularity: security on a scene level for EUMETSAT and product level for others

## Authentication and authorization
1. Backend generates JWT token
1. User has access to products due to belonging to groups and his user roles, access is written in JWT.
1. HAProxy verifies JWT token and forwards it:
    1. to GeoServer gateway, which verifies if WMS request is authorized
    1. to SOK backend, which has internal verification

## TODO:
- [x] Authorization in GeoServer
https://docs.geoserver.org/stable/en/user/security/auth/owsrest.html
Check if authorization can be done by GS
**Resolution**: GeoFence would have to be extended by use, or actively updated based on DB. This is a no-go. We do a custom gateway instead.

- [x] Check if it is possible to build-in JWT authorization into HAproxy
**Resolution**: HAProxy will verify JWT validity, but not enforce scene authorization.

- [x] Check status of HTTPS on S3

- [x] NGINX or HAproxy or BOTH?
**Resolution**: see #50.

**Comment by kmarszalek** [comment]
S3 got https.

**Comment by jswk** [comment]
#50 HAProxy JWT extraction

**Comment by kmarszalek** [comment]
https://docs.geoserver.org/latest/en/user/extensions/geofence/index.html

**Comment by jswk** [comment]
Report on different takes on GS security: external vs internal: https://demo.geo-solutions.it/share/securing_geoserver.pdf.
