### ISSUE TITLE
Milestone 4

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#339]
> Here we can find reference document about S4E requirements. Live document.
> https://docs.cyfronet.pl/x/0IMNB

This issue has been created in order to list all the things which are required for milestone 4.
When relevant issue is created it should be linked in the description here.

## Front End
* [x] Loading state for the sidebar #250
* [x] Connect to TZ aware backend #347
* [ ] Search styling
* [ ] Registration UI / styling (account activation step)
* [ ] Invite UI / styling (account activation step -> might be the same as previous step with some parametrisation)
* [ ] Timeline loading state, general styling
* [ ] General application loading screen (now, when user navigates to app, before JS is loaded there is only a white screen)
* [x] Save configuration [HTML/CSS] #350 
* [ ] Password change #158 
* [ ] Roles system front (?) #170 
* [ ] CSS fixes (Loading opacity, disabled button, disabled input, select) #303 
* [ ] Static pages with information after registration/ Confirmation info etc. [HTML/CSS] #300

## Back End
* [x] Geoserver extension #340 
* [ ] GS-IM data model #371 -> M5
* [ ] Scene and Metadata files data model #69 -> M5
* [ ] Sentinel API compliance #67 -> M5
* [ ] Security, scene level considerations #108 -> M5
* [ ] Registration and synchronization files from s3 with DB #160 -> M5
* [x] Think through the cascades between entities (e.g. AppUser --delete-> PasswordReset | EmailVerification) #358
* [ ] Spring should return `401` error when user is not authenticated (now it always throws 403) -> M5
* [ ] Invite workflow -> M5
* [ ] Mail system for groups and institutions #326 -> M5
* [ ] Institution contains logo, address,etc (note - logos should be optional) -> M5
* [x] Add validation to SavedView thumbnail #286 
* [ ] Better validation #239 -> M5
* [ ] Request throttling #295 -> M5
* [x] Add displayName to ProductType #229 
* [ ] Introduce an option for a persistent developer db #242 -> M5
* [ ] Procedure for adding new ProductTypes #164 -> M5
* [ ] Audit model for DB entites #202 -> M5
* [x] Data set for ZK - s4e-demo-2 #368 

## Infrastructure
* [ ] PoC of extracting JWT token roles #50 -> M5 
* [ ] Data migration to CEPH #57 #82 -> M5
* [ ] Scripts for uploading files to S3 #161 -> M5
* [ ] Email account + production instance configuration #292 (wait for production, see comment in issue)
* [x] Upload of training Sentinel data to CEPH #279
* [x] Improve github actions workflow #351
* [ ] E2E tests follow-up #260 -> M5
* [ ] CI #78 -> M5
* [ ] Harden GeoServer security #14 -> M5
* [ ] HA architecture #161 -> M5 
* [ ] Releases #361 -> M5

## Organizational
* [ ] Project dictionary #163 -> M5 

## For further consideration
* [ ] Map view is full screen, which poses problems when saving it to file (saved image contains more than what the user effectively sees, it also makes zooming in via shift-select unintuitive (part of the zoomed in area can be hidden under sidebar)
