### ISSUE TITLE
Rework Product/Scene schema to fit GS-IM

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#371]
See #340 for more discussion.

- [x] Update GeoServer and change S3Geotiff endpoint to `mailto` #374 
- [x] Change postgresql version to a version with postgis and update the db to the latest version #375 
- [ ] Actually rework the schema and make it work with GS #376
