### ISSUE TITLE
Milestone 5

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#384]
> Here we can find reference document about S4E requirements. Live document.
> https://docs.cyfronet.pl/x/0IMNB

This issue has been created in order to list all the things which are required for [milestone 5](https://github.com/cyfronet-fid/sat4envi/milestone/6).
When relevant issue is created it should be linked in the description here.

## Front End
* [x] Change front to work with new GS ImageMosaic #389
* [x] Fix search places (+add e2e regression tests) #391, #337 and PR #338 
* [x] Dependencies update (e.g. #389, #317)
* [x] Forms #370 

## Back End
* [x] GS-IM data model #371 
* [x] Scene and Metadata files data model #69
* [x] Spring should return `401` error when user is not authenticated (now it always throws 403) #390
* [x] Favourite products #403
* [x] Add more seeds for testing #411
* [x] demo - sql with users, institutions and roles #416

## Infrastructure
* [x] Separate backend and web tests into two jobs in gh-actions #399
* [x] Provide seeds for products and layers for e2e #401
* [x] Check possibility for Prometheus job prioritization #410

See #393 for tickets outside this milestone.
