### ISSUE TITLE
For further consideration

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#393]
* [ ] Map view is full screen, which poses problems when saving it to file (saved image contains more than what the user effectively sees, it also makes zooming in via shift-select unintuitive (part of the zoomed in the area can be hidden under sidebar)

### Graphic design
* [x] Prev for PDF report
* [x] Dedicated settings page for token generation/display and API documentation / navigation to SWAGGER
* [ ] Make notifications more visible
* [x] Design error pages (404, 500, etc)
- [x] Button / Graphic Design for Search sentinel by selected polygon 

### Frontend
* [x] When copying and pasting URL with selected scene that scene is cleared in some cases
* [ ] Style loading timeline (@abacz)
* [ ] Fix issues UIX after tests (@abacz )
* [ ] Purge Group related roles in frontend #747
- [ ] QUICKLOOK (real data!!!!)
- [ ] Lazy loading of sentinel search results
- [ ] Show polygon of hovered sentinel search result
- [ ] Footprint in sentinel search modal (show minimal with polygon on top)
- [ ] Search sentinel by selected polygon
- [ ] Put sentinel search result shape on map on result hover  
- [ ] [Fix] Navigate from login to map after incorrect and then correct authentication #712
* [ ] Update versions of
  - node 12+
  - angular 8+
- [x] Style Settings Dashboards (@abacz) #452  
* [ ] Update PDF report  #380
- [ ] Add "Zapamiętaj mnie" btn while login #179 
- [ ] Dropdown button in settings panel #596 
- [ ] Refactoring [UI] #639
- [ ] Email validation improvement #638 
- [ ] Roles system front-end (???) #170 
* [ ] (Optional) Calendar product loading (when changing month)
* [x] #657 
* [ ] [Fix] Click on institution search in `/settings` shouldn't navigate to page with tiles (settings `start page`)`  #685 
* [x] [Fix] Set locations search value as chosen city name  #682
* [ ] [Fix] Random failing e2e test

### Backend
* [ ] mail for production instance #892
* [x] Procedure for adding new ProductTypes #164 
* [x] Security, scene level considerations #108 
* [x] Institution contains logo, address,etc (note - logos should be optional)
* [x] ZK institution hierarchy vs licenses https://docs.cyfronet.pl/pages/viewpage.action?pageId=71730011
* [x] Introduce an option for a persistent developer db #242 
* [x] [Fix] Invitation mail #561
* [x] Improve changelog generation #612
* [ ] Better validation #239
* [ ] POST/PUT requests should return created/modified content (consolidate behavior across endpoints)
* [ ] Use institution/group/user helper for tests - refactor #637
* [ ] load test - backend search #633
* [ ] load test - backend token usage #631
* [x] Product licenses management #773
* [x] Request throttling #295 

### Infrastructure
* [ ] HA infrastructure #162 
* [ ] Data migration 
* [ ] Data migration to CEPH #57 #82 
* [ ] Scripts for uploading files to S3 #161
* [ ] CI #78 
* [ ] Harden GeoServer security #14 
* [ ] Move static front-end files to S3
* [ ] CEPH->broker->SOK instances
* [ ] Releases #361
* [ ] Update demo instance

### Organizational
* [x] Project dictionary #163 

#### Bugs
* [ ] Button <_Utwórz konto> during registration, it should be disabled until all fields are filled, as well as the <_Zaloguj> button
* [x] Link the /map/products page to sat4envi logo
* [x] Moveable minimap in Generuj raport modal #657 
* [x] consider adding the possibility of removing a Profile by the user or by sending an email to our administrator.
* [x] During registration, the information that the password should contain at least 8 characters is not displayed #787
* [ ] Fix user password change #788 (@danielkryska)
* [x] Refreshing the page causes the return to the login page #789
* [x] Clicking on the dropdown button does not show the sidebar #790
* [ ] The city name is not highlighted during navigating with the arrows #791 (@danielkryska)
* [x] Unnecessary text in the email message (sending a view) #792
* [x] Typos #793
* [x] Sent view and saved view is not loading right after open #794
* [x] Unable to add a new institution #795
* [x] The registration link is not working #796
* [x] Lack of proper validation when changing the password #797
* [x] After adding a new institution, edit the data is not possible #802
* [x] When editing an new instance, all fields are empty and editing create new institution #865
* [x] [Fix] Wrong logo size, extension and try to change image during editing generates an error #804
* [x] Data stored in localStorage is not reset after logging out #806
* [x] No validation for the email field #807
* [ ] Link join institution does not work and button in the invitation aren't visible #809 - button still invisible
* [x] The button <WYŚLIJ DO> does not work (display saved views) #811
* [x] The wrong data is displayed in the user profile #813
* [ ]  [FIX] In the generated report and inconsistent names #815 (@danielkryska)
* [x] Products do not load right away #817
* [ ] Confusing message when trying to generate a token #819 (@danielkryska)
* [x] Information that an email format is required, isn't displayed #820
* [x] Text not wrapping inside a element #825
* [x] Re-invitation to the institution does not work #826
* [x] Possibility to invite the same person to the institution for the second time #827
* [x] After declining the invitation, the link leads to page 404 #833
* [x] It is not possible to remove a person from institution #834 
* [x] Fix adding a user to an institution on invitation acceptance #836
* [x] The search field covers the People field #839
* [ ] RWD problems #840
* [ ] Problem with logging in after making a mistake #841
* [x] Problem with removing the institution #842
* [ ] Button<_WRÓĆ DO POPRZEDNIEJ STRONY> does not work correctly #843
* [ ] Add validation for the cloudCover field (Search data-->Sentinel-2). The field allows to enter letters and special characters (should have number validation  @danielkryska)
* [ ] [Fix] add spacing to a new child in institution list #864 (? @danielkryska)
* [x] When editing an instance, all fields are empty #865
* [ ] [FIX] URL in dashboard and redirection after clicking on the button <_Anuluj> in edit mode and in the mode of adding a new institution #873 (@danielkryska)
* [x] With a lower screen resolution, only the beginning part of the link is clickable #874
* [ ] [Fix] Marking the selected date on the calendar and hour displayed on timeline. #875
* [x] [Fix] Button <_Na żywo> works despite the lack of scenes for the product #890
* [x] [Fix] displaying content in List of institutions #894
* [x] [Fix] url after click on the button <_Osoby w tej instytucji> #895
* [x] [Fix] send request for expert support #902
* [ ] WAITING nad REJECTED near invited person should be written in polish. (@danielkryska)
* [x] [Fix] displaying the message "Odpowiedź serwera nie jest zdjęciem, sprawdź poprawność URL!" #909
* [x] Click on the button <_Zarządzaj> (for admin@mali.pl) should be active all the time, and redirect to /institution instead /profile
* [x] Breadcrumbs for "Twój profil", 'Tablica menedżera:Twój profil:Zmiana hasła' instead 'Tablica menedżera:Zmiana hasła' (Twój profil instead Mój profil and change breadcrums for Zmiana hasła) - new layout doesnt have breadcrumbs for "Twoj profil"
* [x] [Fix] load a saved view #914
* [ ] During changing visible of layers in "Konfiguruj WMS" product shouldn't reload every time.
* [x] [Fix] Search institution #934
* [x] [Fix] Send view and send cofiguration #936
* [x] [Fix] the view displayed after entering the dashboard #944 
* [x] [FIX] adding layers with the same name #947
* [x] [FIX] "Zapisz na dysku jako oryginał (zip)"
* [x] [Fix] register with acceptance of the privacy policy and acceptance button placement #956
* [ ] Problem with the correct search of the town after pressing enter #957 (? @danielkryska)
* [x] [Fix] functionality enabling the enlarged font #958
* [x] Users shouldn't have possibility remove administrator rights for admin@mail.pl
* [ ] [Fix] sending invitation second time on the same mail #959 (@danielkryska)
* [x] Below 1050px resolution there is no WSM LAYER item
* [ ] [FIX] Polygon search update and disappearing polygon after logging in and possibility draw polygon on "Zdjecia satelitarne" #963
* [x]  [Fix] The occurrence of the "Osoby w instytucji", "Warstwy WMS dla instytucji" element for a regular member without administrator privileges #968 
* [x] [Fix] type of request in the e-mail to the expert #978
* [ ] [Fix] legends #979
* [x] [Fix] Timeline displayed when searching for data #981 - decided to not fix it.
* [x] [Fix] redirection to the page after an incorrect login attempt #983
* [ ] [Fix] logo size #988 (change max width 200, @danielkryska)
* [x] [Fix] WMS URL #1000
* [ ] [Fix] Timeline display and loading icon for products without scenes #1001
* [ ] [Fix] "Wczytaj konfigurację" in modal should be replace to name "Konfiguruj WMS" (@danielkryska)
* [ ] [Fix] Save the image configuration #1023
* [ ] Delete "Panel administracyjny" from the user without institution ("Panel administracyjny" and "Twoj profil" move to the same page /settings/profile)

#### Features
* [ ] Add north direction arrow to the map
* [ ] Link partner pages to each partner logo
* [ ] Remove from the map DANMARK
* [ ] Add possibility to removing logo
* [ ] Add an email confirming the account deletion
* [ ] Add functionality for recovery password
* [ ] Add validation for the "Postal code", "Telephone" field for the institution adding form.
* [ ] Icon under the "Akcje" in Institution List, should be changed for something similar to edit data (eg. pencil)
* [ ] Text in "Opis produktu" could be justified.
* [ ] Possibility to edit and copy added wms
* [ ] Polygon after logging in doesn't disappears - #963 (second issue)

### Tests
- [ ] Tests to be done #725

**Comment by AndrzejWojcik** [comment]
@danielkryska The number of letters in "Generuj Raport" is limited, it should be also be limited in "Wyślij widok jako wiadomość"

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK
