### ISSUE TITLE
Milestone 6

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#419]
> Here we can find reference document about S4E requirements. Live document.
> https://docs.cyfronet.pl/x/0IMNB

This issue has been created in order to list all the things which are required for [milestone 6](https://github.com/cyfronet-fid/sat4envi/milestone/7). See #384 for ticket for M5.
When relevant issue is created it should be linked in the description here.

## Graphic design
* [x] Favourite products / Bookmark #404 
* [x] Legends #405
* [ ] Groups and institutions #407 

## Front End
* [x] Style bugfix - modals #359 
* [x] Notifications #423
* [x] Notifications for modal actions #435
* [x] Favourite products #420 
* [ ] Update PDF report (needs more information from @abacz ) #380
* [x] Password change #158
* [ ] Back-office overall fixes #432 
* [x] Selecting place in query does not update input to be the same as selected place #427
* [x] ~~Selecting place in query does not center map (there is slight translation to the right)~~

## Back End
* [x] Add SceneAcceptor driven by files from S3 #160 
* [ ] Sentinel API compliance #67
* [ ] Sentinel search #422
* [x] JWT with assymetric key #428

## Infrastructure
* [ ] PoC of extracting JWT token roles #50 
* [ ] Releases #361

See #393 for tickets outside this milestone.
