### ISSUE TITLE
Milestone 7

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#437]
> Here we can find reference document about S4E requirements. Live document.
> https://docs.cyfronet.pl/x/0IMNB

This issue has been created in order to list all the things which are required for [milestone 7](https://github.com/cyfronet-fid/sat4envi/milestone/8). See #419 for ticket for M6.
When relevant issue is created it should be linked in the description here.

## Graphic design
* [x] Groups and institutions #407 

## Front End
* [x] Back-office overall fixes #430
* [x] Add /logout routing and clear storage on logout (inconsistent state of storage) #445
* [x] [Bugfix] button zapamiętaj mnie don't work (comment it out) #445
* [x] Refactoring  #448
  - [x] RXJS operator (e.g. catchStoreAndThrow(store))
  - [x] removal of console.log's
  - [x] unsubscribe obervables or transform them into promises
## Back End
* [x] Loader of existing scenes from S3 #439 
* [x] Audit model for DB entities #202

## Infrastructure
* [x] PoC of extracting JWT token roles #50 

See #393 for tickets outside this milestone.
