### ISSUE TITLE
Milestone 8

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#458]
> Here we can find reference document about S4E requirements. Live document.
> https://docs.cyfronet.pl/x/0IMNB

This issue has been created in order to list all the things which are required for [milestone 8](https://github.com/cyfronet-fid/sat4envi/milestone/9). See #437 for ticket for M7.
When relevant issue is created it should be linked in the description here.

## Graphic design
* [x] Sentinel search #408 
* [x] Layers manager #406 

## Front End
* [ ] Implement previews for institution / group management (seeds in #411)
  - [ ] Generic List View (see [institutions](https://projects.invisionapp.com/share/S9RJNE8WXUB#/screens/415229205_Ustawienia_-_Instytucje_-_Lista_Wypelniona) and [people](https://projects.invisionapp.com/share/S9RJNE8WXUB#/screens/414649286_Ustawienia__-_Ludzie)) #456
    - [ ] Institutions list view refactor + tests
    - [ ] People list view refactor + tests
  - [ ] Add institution selection into super Admin and Admin settings page [#455](https://github.com/cyfronet-fid/sat4envi/issues/455)
  - [x] Generic Tile View (see [admin](https://projects.invisionapp.com/share/S9RJNE8WXUB#/screens/414649284_Ustawienia) and [superadmin](https://projects.invisionapp.com/share/S9RJNE8WXUB#/screens/414671409_Ustawienia_-_Uberadmin) dashboards #450
    - [x] Superadmin Dashboard
    - [x] Admin Dashboard
  - [ ] Add person form refactor +tests
  - [ ] New / Edit Institution form for superadmin [previev](https://projects.invisionapp.com/share/S9RJNE8WXUB#/screens/415229204_Ustawienia_-_Instytucje_-_Formularz_Dodawania)
* [ ] Update versions of
  - node 12+
  - angular 8+
* [x] UI/API version of application #459
* [ ] Wiring up Sentinel search (depends on backend #422 and prevs #408)

## Back End
* [x] Improve institutions endpoint (`/api/v1/institutions`) to work for any signed in user #457
* [x] Sentinel search #422
* [x] Extension of the groups/institution API (e.g. institution fields, see prevs from #407) #472
* [ ] Sentinel API compliance #67
* [x] Set up and wire up a queue with notifications from S3 to SceneAcceptor #440
* [x] Implement updates in ScenePersiter #469
* [x] Fix Swagger #467
* [ ] GeoServer licensing gateway #479 

## Infrastructure
* [ ] Data migration
* [ ] Releases #361
* [x] Bake tag / commit hash into ENV variable during build process (related to front end `UI/API version of application`)
* [ ] Cancel whole deploy when backend or frontend container does not start / build (do not allow situation where frontend is build from the differnet version than backend)
* [x] Include commit SHA in gh-actions package #461

See #393 for tickets outside this milestone.
