### ISSUE TITLE
Invite user to institution

### ISSUE THREAD

**Issue by kmarszalek** [cyfronet-fid/sat4envi#483]
mail system for groups and institutions #326

#### Flow
- [x] Send invitation with two buttons `[Akceptuj](LOGIN_PAGE_URL_WITH_TOKEN)` and `[Odrzuć](REJECTON_URL)`
  - [ ] Accept
    - [x] Redirect to login page
    - [x] Show a notification `Zaloguj się lub zarejestruj by dołączyć do instytucji`
    - [x] Login or register to authenticate (token in URL)
    - [x] Add user to institution
    - [ ] Redirect to `/settings` page with set institution
    - [ ] Remove invitation on authentication
    - [ ] Send email with confirmation of acceptance
    - [ ] Field `imie i nazwisko` should appear in `/settings/people` table only after acceptance
  - [x] Reject
    - [x] Remove email from invitation list
    - [x] Redirect to main page
    - [x] Show the notification `Zostałeś poprawnie usunięty z listy zaproszeń`
    - [x] Send mail with confirmation of rejecton + ask for re-invitation

#### UI
- [ ] Remove invitation
- [ ] Change recipient of invitation (edit)
- [ ] Table in `/settings/people` should contain new column state

#### Backend
- [x] Create endpoints
  - [x] GET `/invitations`
  - [x] DELETE `/invitations/{token}`
  - [x] PUT `/invitations/{token}` - remove old and create new for new email

#### UI
- [x] Confirm invitation after authentication of user
  - [x] Add a notification `Zaloguj się lub zarejestruj by dołączyć do instytucji` if url contain token
  - [x] Move to `/settings/institution-profile` with active new `institution`
- [x] Reject invitation
  - [x] Add notification `Zostałeś poprawnie usunięty z listy zaproszeń` after redirect from rejecton url

#### UI
- [x] `/settings/people` -> `Dodaj nową osobę` modal should be renamed as `Wyślij zaproszenie`
- [x] Cut out groups functionalities

#### Backend
- [x] Create template for invitation based on [Confirm register](https://projects.invisionapp.com/share/S9RJNE8WXUB#/screens/413514588_Mail_-_Potwierdzenie_Rejestracji)
- [x] Create endpoints 
  - [x] POST `/invitation/:email`
  - [x] PUT (accept) `/invitation/accept/:token`
  - [x] PUT (reject) `/invitation/reject/:token`
- [ ] ~~Invitation should have an expiration date (in the token payload) (for now, the invitation shouldn't be removed)~~

#### DB
- [x] invitation table in DB should be created with fields: `ID`, `email`, `createdAt`, `createdBy`, `updatedAt`, `updatedBy`, `institutionId`, `token`

## GDPR
- [ ] Add `privacy` text to the mail footer? (If you shouldn't see this email remove it)

#### DB
- [ ] Application should have a possibility to remove user details from the system, but keep historical data (anonymous)
- [ ] Add user UUID in application to use it in fields like `createdBy`, `modifiedBy`

---

- [ ] Ask Krzysiek about `Add a new member to the group` (@danielkryska)

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK
