### ISSUE TITLE
Milestone 10

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#509]
> Here we can find reference document about S4E requirements. Live document.
> https://docs.cyfronet.pl/x/0IMNB

This issue has been created in order to list all the things which are required for [milestone 10](https://github.com/cyfronet-fid/sat4envi/milestone/11). See #482 for ticket for M9.
When relevant issue is created it should be linked in the description here.

## Visual frontend
* [x] Legends @abacz  
* [x] Bugfixes @abacz #576 

## Front End
* [x] Add authorization token to image wms layer requests #534
* [x] Generic loader for HTTP requests, navigation events and `open layer` map loading on `/map/products` site #217 
* [x] Institutions and groups styles #493 
* [x] Implement previews for institution / group management (seeds in #411)
  - [x] Generic List View (see [institutions](https://projects.invisionapp.com/share/S9RJNE8WXUB#/screens/415229205_Ustawienia_-_Instytucje_-_Lista_Wypelniona) and [people](https://projects.invisionapp.com/share/S9RJNE8WXUB#/screens/414649286_Ustawienia__-_Ludzie)) #456
    - [x] Institutions list view refactor + tests
  - [x] Change add group and add person to modal #508
    - [x] Refactor add person
    - [x] Write tests for add person
    - [x] Change add person to modal
    - [x] Change add group to modal(https://projects.invisionapp.com/share/S9RJNE8WXUB#/screens/415229204_Ustawienia_-_Instytucje_-_Formularz_Dodawania) #470 
  - [x] Edit institution in `settings/institution` #494 
* [x] Wiring up Sentinel search #532 (depends on backend #422 and prevs #408)
- [x] Change password page #511 
  - [x] Change required fields flags for instition form #510
- [x] Dynamic breadcrumbs + consistent use in whole /settings/* #503
- [x] Add favourites tab in sidebar on `/map/products` site #539 
- [x] Remove active product from map on click on it #557
- [x] [Fix] Institution edition, registration form, add child institution and cancel password change [#558]
- [x] [Fix] Minor fixes #566 
- [x] [Fix] Hide groups and it's functionalities #571 
- [x] Create children tree list in `/settings/institution-profile` #573
* [x] Sentinel quicklooks don't render in s4e-sync-1 #476
- [x] Create dropdown component #592

## Back End
* [x] Sentinel API compliance #67
* [x] Payload validation order should begin with token authorization #481
* [x] endpoint that return scene metadata for search (sentinel) #485
* [x] Fix search scenes endpoint
* [x] Remove dependence on groups in PreAuthorized methods #522
* [x] Allow null in custom validators #491
* [x] Fix SchemaScanner to read from resources correctly #570
* [x] Add products to dataset s4e-sync-1 #578
* [x] fix institutions seeds #496
* [x] Expand search api response #581
* [x] Cookie based authorization #583 
* [x] Set secure flag in token cookie and configure nginx certificate #589
* [x] Correct GeoServer layers parameters #603 

## Infrastructure
* [ ] Releases #361
* [ ] Data migration
* [ ] Update demo instance
* [ ] Semi-production instance (end of June)

## Tests
* [x] Zero test run (unleash inner test Witcher)

See #393 for tickets outside this milestone.

**Comment by jswk** [comment]
Next milestone ticket: #605.
