### ISSUE TITLE
Milestone 11

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#605]
> Here we can find reference document about S4E requirements. Live document.
> https://docs.cyfronet.pl/x/0IMNB

This issue has been created in order to list all the things which are required for [milestone 10](https://github.com/cyfronet-fid/sat4envi/milestone/12). See #509 for ticket for M10.
When relevant issue is created it should be linked in the description here.

## Visual frontend
* [x] Timeline #409

## Front End
* [ ] No Search Result is showing even when results are found #601
* [ ] Stubbed overlay management
* [ ] Add sentinel search modal with details #543
* [x] Add keys handling for search #556 
- [x] Basic institution invitation endpoint #608

## Back End
* [x] Add endpoints to manage Products and Schemas #579 
* [ ] Add admin endpoints to manage Scenes #620
* [ ] Add admin endpoint to trigger synchronization #621
* [x] Trigger creation of views for GeoServer on DB level #622
* [ ] Normalize DB scene table #623 
* [ ] Admin endpoints to manage Scenes and trigger administrative actions #618
* [x] Query param handling in search endpoint #512
* [x] Load testing #165
* [ ] Invite workflow #483 
* [x] Improve scene time filtering performance #610 

## Infrastructure
* [ ] Releases #361
* [ ] Data migration
* [ ] Update demo instance
* [x] Semi-production instance (end of ~June)
* [ ] SOK-Sentry connection

## Tests

See #393 for tickets outside this milestone.
