### ISSUE TITLE
Milestone 12

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#628]
> Here we can find reference document about S4E requirements. Live document.
> https://docs.cyfronet.pl/x/0IMNB

This issue has been created in order to list all the things which are required for [milestone 12](https://github.com/cyfronet-fid/sat4envi/milestone/13). See #605 for ticket for M11.
When relevant issue is created it should be linked in the description here.

## Front End
* [x] Confirm or reject invitation with email URLs in UI #625
- [x] Fix resending invitations and refactor endpoints to not operate on tokens #660
* [x] Add operations on created invitations and status of it #643
* [x] No Search Result is showing even when results are found #601
* [x] Add sentinel search modal with details #543
* [x] Overlay Management UI #614
* [x] ~~Fix ZAPISZ WIDOK functionality #656 - duplicate of #487~~
* [x] ~~#487 (might have become obsolete by moving to secure cookies)~~
* [x] ~~Clear Profile when refreshing REDUX #336~~

## Back End
- [x] Sentinel search details API #663 (related to #543, add missing fields to response, related to #613)
* [x] Create endpoints for created invitations #641
* [x] Add admin endpoints to manage Scenes #620
* [x] Add admin endpoint to trigger synchronization #621
* [x] Normalize DB scene table #623
* [x] `GET /instititons` should return all institutions for admin #551 
* [x] Overlay Management API #615 
* [x] Add HTTP code 429 (`too many attempts`) and logic for it into API #541

## Tests
* [x] Create tickets after Test Run `#4`

See #393 for tickets outside this milestone.

**Comment by danielkryska** [comment]
> > Here we can find reference document about S4E requirements. Live document.
> > https://docs.cyfronet.pl/x/0IMNB
> 
> This issue has been created in order to list all the things which are required for [milestone 12](https://github.com/cyfronet-fid/sat4envi/milestone/13). See #605 for ticket for M11.
> When relevant issue is created it should be linked in the description here.
> ## Visual frontend
> 
>     * [ ]  Add description to `/settings/people` -> `Wyślij zaproszenie` #629
> 
> 
> ## Front End
> 
>     * [ ]  Confirm or reject invitation with email URLs in UI #625
> 
>     * [ ]  Add operations on created invitations and status of it
> 
>     * [ ]  No Search Result is showing even when results are found #601
> 
>     * [ ]  Add sentinel search modal with details #543
> 
>     * [ ]  Overlay Management UI #614
> 
>     * [ ]  New Sentinel Search UI #613
> 
> 
> ## Back End
> 
>     * [ ]  Create endpoints for created invitations
> 
>     * [ ]  Add admin endpoints to manage Scenes #620
> 
>     * [ ]  Add admin endpoint to trigger synchronization #621
> 
>     * [ ]  Normalize DB scene table #623
> 
>     * [ ]  `GET /instititons` should return all institutions for admin
> 
>     * [ ]  Overlay Management API #615
> 
>     * [ ]  Add HTTP code 429 (`too many attempts`) and logic for it into API #541
> 
> 
> ## Infrastructure
> 
>     * [ ]  Releases #361
> 
>     * [ ]  Data migration
> 
>     * [ ]  Update demo instance
> 
>     * [ ]  SOK-Sentry connection
> 
> 
> ## Tests
> 
>     * [ ]  Create tickets after Test Run `#4`
> 
>     * [ ]  New test cases for Test Run `#5`
> 
>     * [ ]  Perform Test Run `#5`
> 
> 
> See #393 for tickets outside this milestone.
