### ISSUE TITLE
Milestone 13

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/sat4envi#672]
> Here we can find reference document about S4E requirements. Live document.
> https://docs.cyfronet.pl/x/0IMNB

This issue has been created in order to list all the things which are required for [milestone 13](https://github.com/cyfronet-fid/sat4envi/milestone/14). See #628 for ticket for M12.
When relevant issue is created it should be linked in the description here.

## Visual frontend
* [x] Prepare SVG icons for product categories #678 
* [x] Management overlays for Institution scope - Admin, Global - Superadmin. #684 
* [x] Extended registration form  #694 

## Front End
* [x] Add description to `/settings/people` -> `Wyślij zaproszenie` #629
* [x] Categories in sidebar (map) #599 
* [ ] New Sentinel Search UI #613 
* [x] Basic timeline functionality (continue work on #667)
* [ ] Changing overlay when no product is selected does not show loading indictor
* [ ] (Optional) Calendar product loading (when changing month)
* [ ] #651 
* [ ] #657 
* [ ] #596
* [x] e2e tests #674

## Back End
* [x] API for getting scenes for products (scenes from last day available) #680
* [x] GDPR (user id instead of email) - after @bwilk consults it with client
* [x] Use admin endpoints instead of SeedProducts #665
* [x] remove group from code #669
* [ ] load test - gs under pressure #632
* [ ] Product Licenses #288
* [ ] Migrate seeds of products to categories and handle them with REST API #671 (@abacz will publish svg icons, they should be added to s3)
* [ ] Add product data (info, legend, etc)
* [x] Describe the process of adding a new product @jswk
* [ ] Add Sentry #687
* [x] Enable actuator endpoints #689 
* [x] Don't use deprecated temporary file name generator #696 

## Infrastructure
* [ ] Releases #361
* [ ] Data migration
* [ ] Update demo instance
* [ ] SOK-Sentry connection

## Tests
* [ ] New test cases for Test Run `#5`
* [ ] Perform Test Run `#5`

See #393 for tickets outside this milestone.
