### ISSUE TITLE
Milestone 14

### ISSUE THREAD

**Issue by kmarszalek** [cyfronet-fid/sat4envi#693]
> Here we can find reference document about S4E requirements. Live document.
> https://docs.cyfronet.pl/x/0IMNB

This issue has been created in order to list all the things which are required for [milestone 13](https://github.com/cyfronet-fid/sat4envi/milestone/15). See #672 for ticket for M13.
When relevant issue is created it should be linked in the description here.

## Visual frontend

* [x] Help request Form / Mail #706 
* [x] Automatic reload of the newest scene (toggle button / UI element) #704 
* [x] Timeline - handling close datapoints #703 
* [x] Handling user with no access to institutions when checking which institution he belongs to
* [x] Available select values in [registration form](https://invis.io/S9RJNE8WXUB#/431384963_Rejestracja), which fields are required and which are optional #702

## Front End
- [ ] Image WMS URL validation #717
- [ ] Image WMS validation
- [x] Create static elements for handling close datapoints #726 
* [x] Dynamic institutions name in settings panel #598
* [x] [Fix] Add institution with form  #683
* [x] E2E tests for Settings' Dashboards #453 
* [ ] Style loading timeline (@abacz)
* [x] New Sentinel Search UI #613 
* [ ] Changing overlay when no product is selected does not show loading indictor
* [ ] Handle anonymous user trying to download sentinel search data (done in part in #613, but further discussion is required concerning handling of the search itself)
* [ ] Preserve sentinel search query in URL (? TBD)
* [ ]  Copy JWT token to clipboard on map in user floating button #713 
- [ ] UI rights system for different types of users #722
* [ ] #651 
* [ ] Implement SVG legends #652 

## Back End
* [ ] Add product data (info, legend, etc)
* [ ] Monitor Project's Results Metrics #699
* [ ] load test - gs under pressure #632
* [x] Migrate seeds of products to categories and handle them with REST API #671 (@abacz will publish svg icons, they should be added to s3)
* [ ] Geoserver cache configuration / optimization #700
* [x] Add Sentry #687
* [x] fix logger #723
* [x] [Fix] DELETE on institution in API #709
* [x] Remove system affecting sudo calls from seed.sh #731
* [x] Recreate DB index on scene.timestamp #735
* [x] Upgrade minio image to 1.2.0 #737

## Infrastructure
* [x] Prometheus monitoring
* [x] SOK-Sentry connection #701
* [ ] HA infrastructure #162 
* [x] Upload images to S3 - Categories, Legends, Emblems - MinIO
* [ ] Data migration 

## Tests
* [ ] New test cases for Test Run `#5`
* [x] Perform Test Run `#5`
* [ ] Perform Test Run `#6` https://docs.google.com/spreadsheets/d/1f4fXaEpLW26cyv3ZGIJNQXU6YEq-HSPttWtzXZTHAbc/edit#gid=0

See #393 for tickets outside this milestone.
