### ISSUE TITLE
Tests to be done

### ISSUE THREAD

**Issue by danielkryska** [cyfronet-fid/sat4envi#725]
## Automatic

Login page

- [x] incorrect login
- [x] niewypełnione pola i błędy

Search

- [ ] Brak elementów w szukajce
- [ ] Poprawność stronicowania
- [ ] Poprawność sortowania
- [ ] Wyszukiwanie specjalnych znaków

Settings people

- [ ] invitation (cypress can  create false email???)
      1. Register and log in with the invitation link
      2. Login with the invitation link
      3. Logged as any user with the session in a browser (12h without login again) and click the invitation link

Search institutions

- [ ] abstract search
- [ ] add new test cases
      - [ ] dashbaord search should be set
      - [ ] should be set from url

API JWT token

- [ ] is it working for API requests?

Register
- [x] Handle captcha -> [solution](https://stackoverflow.com/questions/58684920/cypress-testing-a-contact-form-with-google-recaptcha)

General

- [ ] Clear state of after each test case for all of them
- [ ] Remove `async` notation from each test case (`it`) inside function (linked with simplify tests)
- [ ] Simplify tests

Map Layers

- [x] Update image loading validation `should handle status errors on loading` with all available handled errors types by `image-wms.utils.ts`

Invitations
- [ ] All tests are to repair (send invitation + resend inviation = edit + resend as non-edit)

Layers
- [ ] validation URL

## Manual

- [x] W ogóle czy weszło na stronę błędu (sok.pl/nieistniejąca-trona) -> strona błędu 404
- [ ] Write test cases for Image loading validation (talk with @danielkryska) #764 (wait until merge to master/develop instance)
- [x] Write test cases for Image URL validation (talk with @danielkryska) #720
- [ ] [#722] Hide actions in settings by institution roles

**Comment by kmarszalek** [comment]
https://docs.cyfronet.pl/display/FID/Kierunki+rozwoju+SOK
