### ISSUE TITLE
Missed, incomplete, new functionalities (ui), after user testing

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/sat4envi#739]
**New issues after 4 - 7 user tests https://docs.cyfronet.pl/x/CYVGB**
- [ ] [IMPROVEMENT] - View sharing - change inside target user email into name & surname
- [ ] [CONTENT] - Save view - unificate content: save view -> save configuration
- [ ] [IMPROVEMENT][CONTENT] - rethink about "Szukaj danych" label
- [ ] [BUG] - link doesn't work in email (thunderbird, macos Mail) - backend
- [ ] [IMPROVEMENT] - info about product should appear when user clicks some product first time
- [x] [IMPROVEMENT/BUG?] - Expert help: When expert receive info from user, he can reply (send message) to user email.

**Daniel**

- [x] [MISSING] - Save and list reports templates #798
- [x] [MISSING] - Add 'live' scene loading #799
- [ ] [BUG] - Displaying saved views - product is not loading.  (dev) @ **Fix save view with active product and load it**
- [x] [MISSING] - Help request - modal - https://github.com/cyfronet-fid/sat4envi/issues/706 
- [x] [BUG] Loader should be visible during loading. Scenario: User choose product (loading) he clicks few time looking for scene (button timestamp), map loader is missing. (dev) **Fix fast changed scenes should contain loading indicator #860 **
- [x] [MISSING] - Give administrator privilidge to user in add insitution form and on people page #808
---

- [ ] [ BUG] User profile - need to change layout to same as Institution profile where we have box with user detail and below table with institutions where user is an admin - https://invis.io/S9RJNE8WXUB#/414649288_Ustawienia__-_Profil 
- [x] [BUG] Administrator dashboard (many institutions) - https://invis.io/S9RJNE8WXUB#/421414257_Ustawienia_GR 

--------------------------------------------------------------------------

**Andrzej**

- [x] [REDESIGN] - Favourite products, links visibility (ulubione,produkty) (ui) @abacz 
- [x] [IMPROVEMENT] - switch "star" with "eye"
- [x] [IMPROVEMENT] -put "eyes" with some opacity before products
- [ ] [IMPROVEMENT] - remove image from "share view" email or make it bigger. Now is difficult to see what is happening there.
- [ ] [IMPROVEMENT/BUG] - main loader (product) is not visible

- [x] [REDESIGN] - Timeline. Make it more visible. #887
- [x] [MISSING] - GUI poligon for sentinelsearch @abacz #887 
- [x] [IMPROVEMENT] - Settings: remove "magnifying icon" from sidebar choose institution panel. Add chevron down. #887
- [x] [IMPROVEMENT] - Manage people - justify content, make table 100% width. Add second "invite people" button #887
- [x] [REDESIGN] - Cog icon is not clear in sidebar. Remove or add functionality to this. @abacz  #814 
- [ ] [IMPROVEMENT] - Make footprint bigger (?)
- [x] [CONTENT] - Automatic mails should have info about "Not respond to this email" #739 
- [x] [CONTENT] - Ask expert modal - change text to - look to 7 user tests table - wsparcie eksperckie #739 
- [x]  [CONTENT] - Save view - unificate content: save view -> save configuration #739 
- [x] [CONTENT] - Change "Warstwy" to "Warstwy WMS and "Zarządzaj" to "Zarządzaj WMS" or "Dodaj WMS" #739 

- [x] [REDESIGN] - SentinelSearch - Change cloud icon to sth more popular (ui) @abacz #814 
- [x] [IMPROVEMENT] different icon when user is logged in - need "if" ;) @abacz #814 
- [x] [BUG/IMPROVEMENT] - Text changes in ZK actions (ui) @abacz #814 
- [x] [BUG/IMPROVEMENT] - Text changes in layers (ui) @abacz #814 
- [x] [FOR CONSIDERATION] - Hide institution/people searches @abacz
- [x] [IMPROVEMENT] - add link/button in institution profile to "people management"  @abacz  #814 

--------------------------------------------------------------------------

**Map:**
- [x] [MISSING] - dynamic legends !! (dev/ui) @michal-szostak, @abacz 
- [x] [MISSING] - some products (imgw/ui) @abacz
- [x] [MISSING] - poligon for sentinelsearch @danielkryska, @michal-szostak
- [ ] [MISSING/IMPROVEMENT] - create report - image miniature has no draggable or +/- functionality. PDF raport should has legend and some changed labels (Produkt -> Źródła danych, Data -> Data pozyskania). Product name, geogrid and time zone (UTC) should also appear.(dev) @michal-szostak 

- [ ] [BUG/IMPROVEMENT] if it possible "close datapoints" visible as late as possible  (dev) @abacz 

- [ ] [IMPROVEMENT] smooth layers changing size - now user can't see changing size during dragging (dev)  @danielkryska 
- [ ] [IMPROVEMENT] Button time range (24h-1h). "-" should "zoom-in" the timeline. (dev) @abacz 

**Settings:**

- [x] [IMPROVEMENT] - When new page appear, browser state should show page from top. @danielkryska 
- [ ] [IMPROVEMENT] - different content for modals - Invite people first time/ Resend invitation. @danielkryska @abacz 
- [ ] [BUG] - in institution profile we have "default image" for no institution image state. Now both images are visible. Need to add "if" statement.

**Various:** 
- [x] [FOR CONSIDERATION/IMPROVEMENT] - change left sidebar to top navigation @abacz 
- [ ] [FFC/NEW] - possibility to type scene hour using keyboard
- [ ] [IMPROVEMENT] - MultiSceneBall - is it possible to put scene counter inside (?)
- [ ] [FFC/NEW] - Information about pixel product (hover state)
- [x] [FFC] - is it possible to avoid visible reload all sidebar after adding product to favourites?

**Comment by abacz** [comment]
Moved to confluence.
