### ISSUE TITLE
Milestone 15

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#740]
> Here we can find reference document about S4E requirements. Live document.
> https://docs.cyfronet.pl/x/0IMNB

This issue has been created in order to list all the things which are required for [milestone 15](https://github.com/cyfronet-fid/sat4envi/milestone/16). See #693 for ticket for M14.
When relevant issue is created it should be linked in the description here.

## Front End

* [x] Close data points handling #703 #726
* [x] Create report - image miniature has no draggable or +/- functionality. PDF raport should has legend and some changed labels (Produkt -> Źródła danych, Data -> Data pozyskania). Product name, geogrid and time zone (UTC) should also appear. #657
* [x] Sentinel search result metadata (currently static)
* [x] UI rights system for different types of users #722

^^ must be released before 2020.10.09

* [x] Image WMS URL validation #717
* [ ] Image WMS validation #759
* [ ] Style loading timeline (@abacz)
* [ ] Handle anonymous user trying to download sentinel search data (done in part in #613, but further discussion is required concerning handling of the search itself)
* [ ] Preserve sentinel search query in URL (? TBD)
* [ ] Implement SVG legends #652 
* [ ] Changing overlay when no product is selected does not show loading indicator
* [ ] Purge Group related roles in frontend #747

## Back End

* [x] Pair metadata fields with info presented in the search results (@abacz with @jswk)
* [x] Add scene key to SearchResponse #743
* [x] Send email on registration to an existing email #768

^^ must be released before 2020.10.09

* [x] Product licenses #288
* [ ] Add product data (info, legend, etc)
* [x] Monitor Project's Results Metrics #699
* [ ] load test - gs under pressure #632 
* [ ] Geoserver cache configuration / optimization #700
* [x] Purge Group related roles in backend #746
* [x] Circumvent GHSA-mfwh-5m23-j46w github actions vulnerability #762
* [x] Output info about bucket and schemas in seed.sh #774 
* [x] Allow accessing on the hour EUMETSAT scenes in gs-gateway #776 
* [x] Automatic changelog generation for release #612
* [x] User loged as SuperAdmin (admin@mail.pl) has no possibilities edit data in Institutions on his account. #783

## Infrastructure
* [ ] HA infrastructure #162 
* [ ] Data migration 

## Tests
* [x] New test cases for Test Run `#5`
* [ ] Perform Test Run `#6` https://docs.google.com/spreadsheets/d/1f4fXaEpLW26cyv3ZGIJNQXU6YEq-HSPttWtzXZTHAbc/edit#gid=0

See #393 for tickets outside this milestone.
