### ISSUE TITLE
Implement WCAG 2.0 level AA requirements.

### ISSUE THREAD

**Issue by abacz** [cyfronet-fid/sat4envi#750]
http://www.fdc.org.pl/wcag2/#guidelines

Najważniejsze do sprawdzenia i wdrożenia:

- [ ] **1.4.3** Kontrast 4,5:1. Dla nagłówków i grafiki takiego tekstu 3:1 #755 
- [ ] **1.4.4** Rozmiar tekstu może zostać powiększony do 200% #755 
- [ ] **1.4.5** Niezbędne treści wizualne niosące informacje powinny mieć wersję tekstową
- [ ] **1.4.5** Obrazki opisane Altem
- [ ] **2.1.1** Cała treść oraz wszystkie zawarte w niej funkcjonalności dostępne są z interfejsu klawiatury, bez wymogu określonego czasu użycia poszczególnych klawiszy, poza tymi przypadkami, kiedy dana funkcja wymaga wprowadzenia informacji przez użytkownika w oparciu o ścieżkę ruchów, a nie w oparciu o punkty końcowe wejścia. (Poziom A) 
- [ ] **2.2.1** Użytkownik jest ostrzegany przed upłynięciem limitu czasowego i ma przynajmniej 20 sekund na wydłużenie limitu za pomocą prostej. Tutaj dotyczy to wygaśnięcia sesji. #755 
- [ ]  **2.4.2** Strony internetowe posiadają tytuły, które opisują ich cel lub przedstawiają ich temat. (Poziom A) 
- [ ] **2.4.7** Fokus na aktywnych elementach #755 
- [ ] **3.1.1** Domyślny język naturalny każdej strony internetowej może zostać odczytany przez program komputerowy.
- [ ] **3.2.1** Jeśli jakikolwiek komponent jest oznaczony fokusem, nie powoduje to zmiany kontekstu. (Poziom A) 
- [ ] **3.2.2** Zmiana ustawień jakiegokolwiek komponentu interfejsu użytkownika nie powoduje automatycznej zmiany kontekstu, chyba, że użytkownik został poinformowany o takim działaniu zanim zaczął korzystać z komponentu.  (Poziom A)
- [ ] **3.2.4** Komponenty, które posiadają tę samą funkcjonalność w danym serwisie internetowym, są w taki sam sposób zidentyfikowane. (Poziom AA) 
- [ ] **3.3.1** Jeśli przy wpisywaniu informacji, błąd zostanie wykryty automatycznie, system wskazuje błędny element, a użytkownik otrzymuje opis błędu w postaci tekstu. (Poziom A) 
- [ ] **3.3.2** Pojawiają się etykiety lub instrukcje, kiedy w treści wymagane jest wprowadzenie informacji przez użytkownika. (Poziom A) 
- [ ] **4.1.1** Brak zduplikowanych atrybutów, unikalne ID, pełne znaczniki ergo. HTML zrobiony porządnie -> sprawdzić przy pomocy np. lighthousea.

Check also using this to-do list:
https://romeo.elsevier.com/accessibility_checklist/

**Comment by bwilk** [comment]
@abacz still valid?

**Comment by abacz** [comment]
Yes. We/ve implemented high contrast and bigger font size (small fixes needed)
