### ISSUE TITLE
Milestone 16

### ISSUE THREAD

**Issue by michal-szostak** [cyfronet-fid/sat4envi#785]
> Here we can find reference document about S4E requirements. Live document.
> https://docs.cyfronet.pl/x/0IMNB

This issue has been created in order to list all the things which are required for [milestone 16](https://github.com/cyfronet-fid/sat4envi/milestone/17). See #740 for ticket for M15.
When relevant issue is created it should be linked in the description here.

## Front End

* [ ] Style loading timeline (@abacz)
* [ ] Handle anonymous user trying to download sentinel search data (done in part in #613, but further discussion is required concerning handling of the search itself)
* [ ] Preserve sentinel search query in URL (? TBD)
* [ ] Implement SVG legends #652 
* [ ] Purge Group related roles in frontend #747
* [ ] OL loading indicator is set globally, which causes it to disappear when changing scenes quickly #786
* [ ] Fix issues UIX after tests (@abacz )
* [ ] When copying and pasting URL with selected scene that scene is cleared in some cases

## Back End

* [ ] Add product data (info, legend, etc)
* [ ] load test - gs under pressure #632 
* [ ] Geoserver cache configuration / optimization #700
* [x] Rectangular gaps in GeoServer WMS responses #564
* [x] User loged as SuperAdmin (admin@mail.pl) has no possibilities edit data in Institutions on his account. #783
* [x] Add missing eumetsat_license values #816
* [x] Update the products list #828
* [x] Update local-dataset-1 in minio data directory #830
* [x] Possibility to invite the same person to the institution for the second time #827
* [x] Add scientific domain options to AppUser #835
* [x] Time related problem in search API #838
* [x] Fix message bundle configuration #845 
* [x] Add thumbnail artifact to Sentinel schemas #848

## Infrastructure
* [ ] HA infrastructure #162 
* [ ] Data migration 

## Tests
* [x] Perform Test Run `#6` https://docs.google.com/spreadsheets/d/1f4fXaEpLW26cyv3ZGIJNQXU6YEq-HSPttWtzXZTHAbc/edit#gid=0

See #393 for tickets outside this milestone.

**Comment by kmarszalek** [comment]
closed with https://github.com/cyfronet-fid/sat4envi/releases/tag/v14.1.0
