### ISSUE TITLE
Milestone 17

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/sat4envi#850]
> Here we can find reference document about S4E requirements. Live document.
> https://docs.cyfronet.pl/x/0IMNB

This issue has been created in order to list all the things which are required for [milestone 17](https://github.com/cyfronet-fid/sat4envi/milestone/18). See #785 for ticket for M16.
When relevant issue is created it should be linked in the description here.

## Front End

* [x] Handle anonymous user trying to download sentinel search data (done in part in #613, but further discussion is required concerning handling of the search itself)
* [x] Preserve sentinel search query in URL (? TBD)
* [x] Implement SVG legends #652 
* [x] OL loading indicator is set globally, which causes it to disappear when changing scenes quickly #786

## Back End

* [x] load test - gs under pressure #632 
* [x] Add ZK option to Institution #862
* [x] Geoserver cache configuration / optimization #700
* [x] Improve property validation and handle custom static path #855
* [x] Handle delete S3 object notifications #858
* [x] Make sure download endpoints require authenticated user #868
* [x] Add info and proper examples to apihowto.component 

## GeoServer

* [x] Configure S3 GeoWebCache cyfronet-fid/docker-geoserver#6
* [x] Release fiddev/geoserver 1.6.0-GS2.18.0 cyfronet-fid/docker-geoserver#7

## Infrastructure
* [ ] HA infrastructure #162 
* [ ] Data migration 

## Tests
* [x] test search and download API #854

See #393 for tickets outside this milestone.
