### ISSUE TITLE
Milestone 18

### ISSUE THREAD

**Issue by kmarszalek** [cyfronet-fid/sat4envi#881]
> Here we can find reference document about S4E requirements. Live document.
> https://docs.cyfronet.pl/x/0IMNB

This issue has been created in order to list all the things which are required for [milestone 18](https://github.com/cyfronet-fid/sat4envi/milestone/19). See #850 for ticket for M17.
When relevant issue is created it should be linked in the description here.

## Front End

* [x] Handle anonymous user trying to download sentinel search data (done in part in #613, but further discussion is required concerning handling of the search itself) #928
* [x] Preserve sentinel search query in URL #928
* [x] Implement SVG legends #652 
* [x] OL loading indicator is set globally, which causes it to disappear when changing scenes quickly #786

## Back End

* [x] load test - gs under pressure #632 
* [x] search API count #907
* [x] rodo endpoint for user and admin /forgetme #918

## Tests

See #393 for tickets outside this milestone.
